# Generated by Django 4.2.6 on 2023-11-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_app', '0002_remove_posts_liked_by_remove_usermodel_liked_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by', through='plat_app.Likes', to='plat_app.usermodel'),
        ),
    ]
